var majorlist = [    
"Art@School of Arts and Sciences(SAS)",
"Art History@School of Arts and Sciences(SAS)",
"Astrophysics@School of Arts and Sciences(SAS)",
"Biomathematics@School of Arts and Sciences(SAS)",
"Cell & Developmental Biology@School of Arts and Sciences(SAS)",
"Cell Biology & Neuroscience@School of Arts and Sciences(SAS)",
"Chemistry@School of Arts and Sciences(SAS)",
"Chinese@School of Arts and Sciences(SAS)",
"Classics@School of Arts and Sciences(SAS)",
"Comparative Literature@School of Arts and Sciences(SAS)",
"Computer Science@School of Arts and Sciences(SAS)",
"Criminal Justice@School of Arts and Sciences(SAS)",
"East Asian Language and Cultures@School of Arts and Sciences(SAS)",
"East Asian Languages and Area Studies@School of Arts and Sciences(SAS)",
"Economics@School of Arts and Sciences(SAS)",
"English@School of Arts and Sciences(SAS)",
"African Languages & Literature@School of Arts and Sciences(SAS)",
"Africana Studies@School of Arts and Sciences(SAS)",
"American Studies@School of Arts and Sciences(SAS)",
"Anthropology@School of Arts and Sciences(SAS)",
"Applied Mathematics@School of Arts and Sciences(SAS)",
"European Studies@School of Arts and Sciences(SAS)",
"Exercise Science and Sport Studies@School of Arts and Sciences(SAS)",
"French@School of Arts and Sciences(SAS)",
"Genetics@School of Arts and Sciences(SAS)",
"Geography@School of Arts and Sciences(SAS)",
"Geological Sciences@School of Arts and Sciences(SAS)",
"German@School of Arts and Sciences(SAS)",
"History@School of Arts and Sciences(SAS)",
"History and Political Science@School of Arts and Sciences(SAS)",
"Italian@School of Arts and Sciences(SAS)",
"Jewish Studies@School of Arts and Sciences(SAS)",
"Latin American Civilization Studies@School of Arts and Sciences(SAS)",
"Latino and Hispanic Caribbean Studies@School of Arts and Sciences(SAS)",
"Linguistics@School of Arts and Sciences(SAS)",
"Mathematics@School of Arts and Sciences(SAS)",
"Medical Technology@School of Arts and Sciences(SAS)",
"Medieval Studies@School of Arts and Sciences(SAS)",
"Middle Eastern Studies@School of Arts and Sciences(SAS)",
"Molecular Biology & Biochemistry@School of Arts and Sciences(SAS)",
"Philosophy@School of Arts and Sciences(SAS)",
"Physics and Astronomy@School of Arts and Sciences(SAS)",
"Political Science@School of Arts and Sciences(SAS)",
"Portugese@School of Arts and Sciences(SAS)",
"Psychology@School of Arts and Sciences(SAS)",
"Public Policy@School of Arts and Sciences(SAS)",
"Religion@School of Arts and Sciences(SAS)",
"Russian@School of Arts and Sciences(SAS)",
"Sociology@School of Arts and Sciences(SAS)",
"Spanish@School of Arts and Sciences(SAS)",
"Statistics@School of Arts and Sciences(SAS)",
"Visual Arts@School of Arts and Sciences(MGSA)",
"Women's & Gender Studies@School of Arts and Sciences(SAS)",
"Agricultural and Food Systems@School of Environmental and Biological Sciences(SEBS)",
"Animal Sciences@School of Environmental and Biological Sciences(SEBS)",
"Biochemistry@School of Environmental and Biological Sciences(SEBS)",
"Biological Sciences@School of Environmental and Biological Sciences(SEBS)",
"Biology@School of Environmental and Biological Sciences(SEBS)",
"Biotechnology@School of Environmental and Biological Sciences(SEBS)",
"Ecology@School of Environmental and Biological Sciences(SEBS)",
"Ecology and Evolution@School of Environmental and Biological Sciences(SEBS)",
"Ecology and Natural Resources@School of Environmental and Biological Sciences(SEBS)",
"Entomology@School of Environmental and Biological Sciences(SEBS)",
"Environmental & Business Economics@School of Environmental and Biological Sciences(SEBS)",
"Environmental Planning & Design@School of Environmental and Biological Sciences(SEBS)",
"Environmental Policy@School of Environmental and Biological Sciences(SEBS)",
"Environmental Sciences@School of Environmental and Biological Sciences(SEBS)",
"Food Science@School of Environmental and Biological Sciences(SEBS)",
"Landscape Architecture@School of Environmental and Biological Sciences(SEBS)",
"Marine Sciences@School of Environmental and Biological Sciences(SEBS)",
"Metereology@School of Environmental and Biological Sciences(SEBS)",
"Microbiology@School of Environmental and Biological Sciences(SEBS)",
"Nutrition@School of Environmental and Biological Sciences(SEBS)",
"Nutritional Sciences@School of Environmental and Biological Sciences(SEBS)",
"Oceanography@School of Environmental and Biological Sciences(SEBS)",
"Plant Biology@School of Environmental and Biological Sciences(SEBS)",
"Dance@Mason Gross School of the Arts(MGSA)",
"Dance Education@Mason Gross School of the Arts(MGSA)",
"Design of Learning Environments@Mason Gross School of the Arts(MGSA)",
"Music@Mason Gross School of the Arts(MGSA)",
"Theater Arts@Mason Gross School of the Arts(MGSA)",
"Pharmaceutical Science@Ernest Mario School of Pharmacy(EMSP)",
"Pharmacology Cellular and Molecular@Ernest Mario School of Pharmacy(EMSP)",
"Accounting@Rutgers Business School(RBS)",
"Business Analytics and Information Technology@Rutgers Business School(RBS)",
"Business@Rutgers Business School(RBS)",
"Supply Chain and Marketing Science@Rutgers Business School(RBS)",
"Finance@Rutgers Business School(RBS)",
"Financial and Risk Mgmt@Rutgers Business School(RBS)",
"Management@Rutgers Business School(RBS)",
"Marketing@Rutgers Business School(RBS)",
"Communication@School of Communication and Information(SCI)",
"Communication and Information Studies@School of Communication and Information(SCI)",
"Information Technology and Informatics@School of Communication and Information(SCI)",
"Journalism@School of Communication and Information(SCI)",
"Journalism and Media Studies@School of Communication and Information(SCI)",
"Applied Sciences in Engineering@School of Engineering(SOE)",
"Bioenvironmental Engineering@School of Engineering(SOE)",
"Biomedical Engineering@School of Engineering(SOE)",
"Chemical Engineering@School of Engineering(SOE)",
"Civil & Environmental Engineering@School of Engineering(SOE)",
"Electrical & Computer Engineering@School of Engineering(SOE)",
"Industrial and Systems Engineering@School of Engineering(SOE)",
"Materials Science and Engineering@School of Engineering(SOE)",
"Mechanical Engineering@School of Engineering(SOE)",
"Planning and Public Policy@Edward J. Bloustein School of Planning and Public Policy(EBSPPP)",
"Public Health@Edward J. Bloustein School of Planning and Public Policy(EBSPPP)",
"Urban Planning & Policy Development@Edward J. Bloustein School of Planning and Public Policy(EBSPPP)",
"Human Resource Management@School of Management and Labor Relations(SMLR)",
"Labor Studies and Employment Relations@School of Management and Labor Relations(SMLR)",
"Labor and Employment Relations@School of Management and Labor Relations(SMLR)",
"Social Studies Education@School of Social Work(SSW)",
"Social Work@School of Social Work(SSW)",
"Admin and Supervision of Education@Other(Other Majors)",
"Adult and Continuing Education@Other(Other Majors)",
"Agricultural Economics@Other(Other Majors)",
"Agricultural Science@Other(Other Majors)",
"All Majors@Other(Other Majors)", 
"Atmospheric Science@Other(Other Majors)",
"Clinical Psychology@Other(Other Majors)",
"Computational Biology & Molecular Biophysics@Other(Other Majors)",
"Counseling Psychology@Other(Other Majors)",
"Education@Other(Other Majors)",
"Education Culture and Society@Other(Other Majors)",
"Educational Leadership@Other(Other Majors)",
"Educational Statistics and Measurements@Other(Other Majors)",
"Endocrinology and Animal Biosciences@Other(Other Majors)",
"Evolution and Natural Resources@Other(Other Majors)",
"Food and Business Economics@Other(Other Majors)",
"Institutions and Behavior@Other(Other Majors)", 
"Language Education@Other(Other Majors)",
"Learning Cognition and Development@Other(Other Majors)",
"Library and Information Studies@Other(Other Majors)",
"Literacy Education@Other(Other Majors)",
"Mathematical Finance@Other(Other Majors)",
"Mathematics Education@Other(Other Majors)",
"Medicinal Chemistry@Other(Other Majors)",
"Neuroscience@Other(Other Majors)",
"Operations Research@Other(Other Majors)",
"Organizational Psychology@Other(Other Majors)",
"Physiology and Integrative Biology@Other(Other Majors)",
"Plant Science@Other(Other Majors)",
"Public Administration@Other(Other Majors)",
"Quantitative Finance@Other(Other Majors)",
"Reading Education@Other(Other Majors)",
"Reading Recovery@Other(Other Majors)",
"Religious Studies@Other(Other Majors)",
"School Psychology@Other(Other Majors)",
"Science Education@Other(Other Majors)",
"Special Education@Other(Other Majors)",
"Teacher Leadership@Other(Other Majors)",
"Toxicology@Other(Other Majors)",
    ];
    
    
    
var majorlist2 = [    
"Agricultural Economics@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Agricultural Science@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Agricultural and Food Systems@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Animal Sciences@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Biochemistry@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Biological Sciences@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Biology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Biomathematics@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Biotechnology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Cell & Developmental Biology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Cell Biology & Neuroscience@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Computational Biology & Molecular Biophysics@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Ecology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Ecology and Evolution@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Ecology and Natural Resources@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Endocrinology and Animal Biosciences@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Entomology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Environmental & Business Economics@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Environmental Planning & Design@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Environmental Policy@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Environmental Sciences@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Food Science@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Food and Business Economics@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Landscape Architecture@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Marine Sciences@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Metereology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Microbiology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Molecular Biology & Biochemistry@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Nutrition@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Nutritional Sciences@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Oceanography@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Physiology and Integrative Biology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Plant Biology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Plant Science@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Genetics@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Medical Technology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Medicinal Chemistry@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Neuroscience@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Pharmaceutical Science@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Pharmacology Cellular and Molecular@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Toxicology@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Evolution and Natural Resources@Biological Agricultural and Environmental Sciences Majors(Bio, Agri & Env Majors)",
"Astrophysics@Physical Science Majors(Physical Science Majors)",
"Physics and Astronomy@Physical Science Majors(Physical Science Majors)",
"Atmospheric Science@Physical Science Majors(Physical Science Majors)",
"Chemistry@Physical Science Majors(Physical Science Majors)",
"Geological Sciences@Physical Science Majors(Physical Science Majors)",
"Applied Mathematics@Computer Mathematics and Statistics Majors(Comp, Math & Stats Majors)",
"Computer Science@Computer Mathematics and Statistics Majors(Comp, Math & Stats Majors)",
"Mathematical Finance@Computer Mathematics and Statistics Majors(Comp, Math & Stats Majors)",
"Mathematics@Computer Mathematics and Statistics Majors(Comp, Math & Stats Majors)",
"Statistics@Computer Mathematics and Statistics Majors(Comp, Math & Stats Majors)",
"Applied Sciences in Engineering@Engineering Majors(Engineering Majors)",
"Bioenvironmental Engineering@Engineering Majors(Engineering Majors)",
"Biomedical Engineering@Engineering Majors(Engineering Majors)",
"Chemical Engineering@Engineering Majors(Engineering Majors)",
"Civil & Environmental Engineering@Engineering Majors(Engineering Majors)",
"Electrical & Computer Engineering@Engineering Majors(Engineering Majors)",
"Industrial and Systems Engineering@Engineering Majors(Engineering Majors)",
"Materials Science and Engineering@Engineering Majors(Engineering Majors)",
"Mechanical Engineering@Engineering Majors(Engineering Majors)",
"Accounting@Business Majors(Business Majors)",
"Business Analytics and Information Technology@Business Majors(Business Majors)",
"Finance@Business Majors(Business Majors)",
"Financial and Risk Mgmt@Business Majors(Business Majors)",
"Management@Business Majors(Business Majors)",
"Marketing@Business Majors(Business Majors)",
"Supply Chain and Marketing Science@Business Majors(Business Majors)",
"Quantitative Finance@Business Majors(Business Majors)",
"Business@Business Majors(Business Majors)",
"Operations Research@Business Majors(Business Majors)",
"Communication@Communications Majors(Communications Majors)",
"Communication and Information Studies@Communications Majors(Communications Majors)",
"Information Technology and Informatics@Communications Majors(Communications Majors)",
"Journalism@Communications Majors(Communications Majors)",
"Journalism and Media Studies@Communications Majors(Communications Majors)",
"All Majors@Unspecified(Unspecified)", 
"Institutions and Behavior@Social Science Majors(Social Science Majors)",
"Clinical Psychology@Social Science Majors(Social Science Majors)",
"Counseling Psychology@Social Science Majors(Social Science Majors)",
"Learning Cognition and Development@Social Science Majors(Social Science Majors)",
"Organizational Psychology@Social Science Majors(Social Science Majors)",
"Psychology@Social Science Majors(Social Science Majors)",
"School Psychology@Social Science Majors(Social Science Majors)",
"Geography@Social Science Majors(Social Science Majors)",
"Anthropology@Social Science Majors(Social Science Majors)",
"Criminal Justice@Social Science Majors(Social Science Majors)",
"Economics@Social Science Majors(Social Science Majors)",
"Exercise Science and Sport Studies@Social Science Majors(Social Science Majors)",
"Human Resource Management@Social Science Majors(Social Science Majors)",
"Labor Studies and Employment Relations@Social Science Majors(Social Science Majors)",
"Labor and Employment Relations@Social Science Majors(Social Science Majors)",
"Planning and Public Policy@Social Science Majors(Social Science Majors)",
"Political Science@Social Science Majors(Social Science Majors)",
"Public Administration@Social Science Majors(Social Science Majors)",
"Public Health@Social Science Majors(Social Science Majors)",
"Public Policy@Social Science Majors(Social Science Majors)",
"Social Studies Education@Social Science Majors(Social Science Majors)",
"Social Work@Social Science Majors(Social Science Majors)",
"Sociology@Social Science Majors(Social Science Majors)",
"Urban Planning & Policy Development@Social Science Majors(Social Science Majors)",
"Women's & Gender Studies@Social Science Majors(Social Science Majors)",
"Mathematics Education@Education Majors(Education Majors)",
"Admin and Supervision of Education@Education Majors(Education Majors)",
"Adult and Continuing Education@Education Majors(Education Majors)",
"Education@Education Majors(Education Majors)",
"Education Culture and Society@Education Majors(Education Majors)",
"Educational Leadership@Education Majors(Education Majors)",
"Educational Statistics and Measurements@Education Majors(Education Majors)",
"Reading Education@Education Majors(Education Majors)",
"Reading Recovery@Education Majors(Education Majors)",
"Science Education@Education Majors(Education Majors)",
"Special Education@Education Majors(Education Majors)",
"Literacy Education@Education Majors(Education Majors)",
"Teacher Leadership@Education Majors(Education Majors)",
"Art@Visual and Performing Arts Majors(Arts Majors)",
"Dance@Visual and Performing Arts Majors(Arts Majors)",
"Dance Education@Visual and Performing Arts Majors(Arts Majors)",
"Design of Learning Environments@Visual and Performing Arts Majors(Arts Majors)",
"Music@Visual and Performing Arts Majors(Arts Majors)",
"Theater Arts@Visual and Performing Arts Majors(Arts Majors)",
"Visual Arts@Visual and Performing Arts Majors(Arts Majors)",
"Art History@Liberal Arts and History Majors(Liberal Arts Majors)",
"Classics@Liberal Arts and History Majors(Liberal Arts Majors)",
"Comparative Literature@Liberal Arts and History Majors(Liberal Arts Majors)",
"European Studies@Liberal Arts and History Majors(Liberal Arts Majors)",
"History@Liberal Arts and History Majors(Liberal Arts Majors)",
"History and Political Science@Liberal Arts and History Majors(Liberal Arts Majors)",
"Library and Information Studies@Liberal Arts and History Majors(Liberal Arts Majors)",
"Linguistics@Liberal Arts and History Majors(Liberal Arts Majors)",
"Philosophy@Liberal Arts and History Majors(Liberal Arts Majors)",
"Religion@Liberal Arts and History Majors(Liberal Arts Majors)",
"Religious Studies@Liberal Arts and History Majors(Liberal Arts Majors)",
"African Languages & Literature@Literature and Languages Majors(Lit & Lang Majors)",
"Africana Studies@Literature and Languages Majors(Lit & Lang Majors)",
"American Studies@Literature and Languages Majors(Lit & Lang Majors)",
"Chinese@Literature and Languages Majors(Lit & Lang Majors)",
"East Asian Language and Cultures@Literature and Languages Majors(Lit & Lang Majors)",
"East Asian Languages and Area Studies@Literature and Languages Majors(Lit & Lang Majors)",
"English@Literature and Languages Majors(Lit & Lang Majors)",
"French@Literature and Languages Majors(Lit & Lang Majors)",
"German@Literature and Languages Majors(Lit & Lang Majors)",
"Italian@Literature and Languages Majors(Lit & Lang Majors)",
"Jewish Studies@Literature and Languages Majors(Lit & Lang Majors)",
"Language Education@Literature and Languages Majors(Lit & Lang Majors)",
"Latin American Civilization Studies@Literature and Languages Majors(Lit & Lang Majors)",
"Latino and Hispanic Caribbean Studies@Literature and Languages Majors(Lit & Lang Majors)",
"Medieval Studies@Literature and Languages Majors(Lit & Lang Majors)",
"Middle Eastern Studies@Literature and Languages Majors(Lit & Lang Majors)",
"Portugese@Literature and Languages Majors(Lit & Lang Majors)",
"Russian@Literature and Languages Majors(Lit & Lang Majors)",
"Spanish@Literature and Languages Majors(Lit & Lang Majors)",
    ];